#!/bin/bash
# List files in the current directory
echo "Files in current directory:"
ls -al
# Move to the parent directory
cd ..
# List files in the parent directory
echo "Files in parent directory:"
ls -al
# Move to the /boot directory
cd /boot
# List files in the /boot directory
echo "Files in /boot directory:"
ls -al
